version: '3.8'

services:
  db:
    restart: always
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=main"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 --workers 6 shoonya_backend.wsgi
    volumes:
      - ./backend/:/usr/src/backend/
      - static_volume:/usr/src/backend/static
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  redis:
    image: "redis"

volumes:
  postgres_data:
  static_volume:
