apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-rules
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  tls:
  - hosts:
    - django-aks-ingress.westus.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: django-aks-ingress.westus.cloudapp.azure.com
    http:
      paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: shoonya-web
              port: 
                number: 80